name: "Terraform Automation and Validation"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "Check and Validate"
    runs-on: ubuntu-latest
    
    # We set the working directory to assignment4 
    # since that's where your provider/module logic is.
    defaults:
      run:
        working-directory: ./assignment4

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Format Check
        # This checks if your code is indented correctly
        run: terraform fmt -check

      - name: Terraform Validate
        # This checks for syntax errors (missing brackets, typos)
        run: terraform validate

      - name: Terraform Plan
        # This simulates the infrastructure build
        run: terraform plan -no-color